name: example_for_oktoast
description: A new Flutter project.
version: 3.2.0+2
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  oktoast:
    path: ../

flutter:
  uses-material-design: true
